### ISSUE TITLE
 Module not found: Can't resolve 'stencil-text-skeleton-loader-react' in 'react-projetct/src/components'

### ISSUE THREAD

**Issue by lucascco** [ionic-team/stencil-ds-react-template#5]
This error happen when I try import the component from wrapper react project.

```html
import { TextSkeletonLoader } from 'stencil-text-skeleton-loader-react';
```

Here is web component project built in StencilJs
https://github.com/lucascco/stencil-text-skeleton-loader

Here is the wrapper in React
https://github.com/lucascco/stencil-text-skeleton-loader-react

Could anyone help me about this issue?
Many thanks.

**Comment by alexandertrefz** [comment]
After the last commit the file `./dist/index.cjs.js` doesnt get created anymore. The `package.json` field `main` is referencing it however. Changing this field to `./dist/index.js` fixed this for me.

**Comment by lucascco** [comment]
Thanks @alexandertrefz . It's also work for me.
